# Irá exibir uma mensagem de Olá Mundo na Tela.

# O @ é para que o programa só de print no Hello, World e não no comando inteiro echo "Hello, World". Basicamente ele indica que essa execução será um 
# Execução silenciosa

all:
	
	@echo "Hello, World" 