# O all é um alvo que tem prioridade. Então quando eu executar o progrma Make, ele vai prioritariamente procurar por esse alvo "all" e executar 
# O comando ou a ação que esteja atribuido a esse alvo. Como ele não precisa de nada nesse caso, não há necessidade para procurar por uma dependencia para 
# Executar esse alvo "all"
all:	mensagem	mensagem2
	@echo "Hello, World!"

# Outro alvo, dessa vez chamada mensagem
mensagem:
	@echo "Oi, eu sou o alvo mensagem"

mensagem2:
	@echo "Sou o alvo mensagem2"

mensagem3:
	@echo "Sou o alvo mensagem3"