name: C/C++ CI

on:
  push:
    branches:
      - release/*
      - waiting_room
  pull_request:
    branches: 
      - release/*
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Where I am now
      run: pwd
    - name: Execute
      run: .home/runner/work/cClass/cClass/Estruturas_E_Unioes/exercicio3
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
